name: AWS CodeCommit Mirror

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, delete]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mirroring"
  mirroring:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: unnecessary
        if_key_exists: replace

    - name: copy to home
      run: |
        mkdir -p ~/work/_temp/_github_home/
        cp -ar ~/.ssh ~/work/_temp/_github_home/

    - name: Install Dependencies
      run: |
        pip install --upgrade setuptools
        pip install backports.functools-lru-cache
        pip install backports.weakref
        sudo pip install pipenv
        pipenv install

    - uses: actions/checkout@v2
    - name: Mirror Github Repositories to AWS CodeCommit
      run: |
        pipenv run python3 src/github-aws-commit-mirror.py

    # - name: Debug
    #   run: |
    #     pwd
    #     ls ~/.ssh
    #     cat /home/runner/.ssh/id_rsa

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/testrepo
        ssh_private_key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}

